version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm ci
      - npx nx run client:build:production
# Include only the files required for your application to run.
artifacts:
  files:
    - "**/*"
  base-directory: "dist/apps/client"
