on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
      - uses: actions/checkout@v4
      - name: Develop Deployment
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config --global user.name 'bot'
          git config --global user.email 'bot@moveohls.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout -b "development"
          git reset --hard "$GITHUB_REF_NAME"
          git push -f origin development

